# 開発環境
FROM node:17-slim
WORKDIR /usr/src/app

# cypress用
RUN apt update
RUN apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb